- name: Kubernetes v Azure
  href: ./index.yml
- name: Přehled
- name: Rychlé starty
  expanded: true
- name: Kurzy
- name: Koncepty
- name: Návody
  items:
    - name: Zachování data s Azure Files
      href: ../../aks/azure-files.md?toc=%2fazure%2fcontainer-service%2fkubernetes%2ftoc.json
    - name: Monitorování
    - name: Nasazení aplikací Spring Boot
      items:
        - name: Nasazení aplikace Spring Boot Application v Linuxu ve službě Azure Container Service
          href: container-service-deploy-spring-boot-app-on-linux.md
        - name: Nasazení aplikace Spring Boot Application v clusteru Kubernetes ve službě Azure Container Service
          href: container-service-deploy-spring-boot-app-on-kubernetes.md
        - name: Nasazení aplikace Spring Boot s využitím modulu plug-in fabric8 Maven
          href: container-service-deploy-spring-boot-app-using-fabric8-maven-plugin.md
- name: Referenční informace
  items:
    - name: Azure CLI
      href: /cli/azure/acs
    - name: PowerShell
      href: /powershell/module/az.compute
    - name: REST
      href: /rest/api/container-service
- name: Zdroje a prostředky
  items:
    - name: Plány Azure do budoucna
      href: 'https://azure.microsoft.com/roadmap/'
    - name: Šablony – modul ACS
      href: 'https://github.com/Azure/acs-engine'
    - name: Ceny
      href: 'https://azure.microsoft.com/pricing/details/container-service/'
    - name: Dostupnost v oblastech
      href: 'https://azure.microsoft.com/regions/services/'
    - name: Stack Overflow
      href: 'https://stackoverflow.com/questions/tagged/azure-container-service'
    - name: Videa
      href: 'https://azure.microsoft.com/resources/videos/index/?services=container-service&sort=newest'