### YamlMime:Landing
title: Kubernetes s podporou Azure Arc (Preview)
summary: Další informace o postupu při správě clusterů Kubernetes s využitím služby Azure Arc
metadata:
  title: Kubernetes s podporou Azure Arc
  description: Další informace o správě místních počítačů v Azure
  author: 
  ms.service: azure-arc
  ms.topic: landing-page
  ms.date: 06/26/2020
  ms.author: 
  ms.openlocfilehash: 9eeddfefe451eb524484df8a1986c7ec736c4c0f
  ms.sourcegitcommit: d79513b2589a62c52bddd9c7bd0b4d6498805dbe
  ms.translationtype: HT
  ms.contentlocale: cs-CZ
  ms.lasthandoff: 12/18/2020
  ms.locfileid: "97674368"
landingContent:
- title: Připojení clusterů Kubernetes k Azure s využitím služby Azure Arc
  linkLists:
  - linkListType: overview
    links:
    - text: Co je Kubernetes s podporou Azure Arc?
      url: overview.md
  - linkListType: quickstart
    links:
    - text: Připojení clusteru
      url: connect-cluster.md
  - linkListType: how-to-guide
    links:
    - text: Nasazení konfigurací s využitím GitOps
      url: use-gitops-connected-cluster.md
    - text: Nasazení diagramů Helmu s využitím GitOps
      url: use-gitops-with-helm.md
    - text: Vynucení GitOps s využitím Azure Policy
      url: use-azure-policy.md
    - text: Nasazení úloh Azure IoT Edge
      url: deploy-azure-iot-edge-workloads.md
- title: Testování konceptu
  linkLists:
  - linkListType: sample
    links:
    - text: Rychlé zprovoznění
      url: https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_k8s/
- title: Referenční architektura
  linkLists:
  - linkListType: architecture
    links:
    - text: Správa nasazení a konfigurací pro hybridní clustery Kubernetes
      url: /azure/architecture/hybrid/arc-hybrid-kubernetes
